### ISSUE TITLE
Improve the suggestion

### ISSUE THREAD

**Issue by Adyel** [OpenBangla/OpenBangla-Keyboard#51]
![screenshot from 2018-06-23 19-38-19c](https://user-images.githubusercontent.com/4653623/41810255-6a1a0e94-771d-11e8-988e-6042eb3972b8.png)

OBK feels great except when it comes to suggestion. While writing, it keeps giving bad suggestion no matter how many time you change it. Can we make it so that it will suggest the most used words first?

**Comment by mominul** [comment]
I think this has been fixed by #41

**Comment by Adyel** [comment]
@mominul Still not working for me. I am using the latest ver.

**Comment by mominul** [comment]
Have you compiled from `master` source?

**Comment by Adyel** [comment]
@mominul No, I thought it was included in `1.4`?

**Comment by mominul** [comment]
No, this feature will be available in the next version.
